CREATE SEQUENCE location_id_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE employee_id_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE attachment_id_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE assignment_id_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE auth_id_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE car_id_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE request_id_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE route_id_sequence START WITH 1 INCREMENT BY 1;